
@echo off

REM !!! Generated by the fmp-cli 1.84.0.  DO NOT EDIT!

md MediaCarousel\Assets\3rd\fmp-xtc-mediacarousel

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-mediacarousel-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\MediaCarousel\Assets\3rd\fmp-xtc-mediacarousel\
